// <auto-generated />
using System;
using Allasinterju.Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Allasinterju.Database.Migrations
{
    [DbContext(typeof(AllasinterjuContext))]
    [Migration("20241016082647_InitialM")]
    partial class InitialM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Allasinterju.Database.Models.Allas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cegid")
                        .HasColumnType("int")
                        .HasColumnName("cegid");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cim");

                    b.Property<DateTime?>("Hatarido")
                        .HasColumnType("datetime")
                        .HasColumnName("hatarido");

                    b.Property<TimeOnly?>("Kitoltesido")
                        .HasColumnType("time")
                        .HasColumnName("kitoltesido");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("leiras");

                    b.Property<string>("Munkakor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("munkakor");

                    b.Property<string>("Munkarend")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("munkarend");

                    b.Property<string>("Rovidleiras")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rovidleiras");

                    b.Property<int>("Telephelyid")
                        .HasColumnType("int")
                        .HasColumnName("telephelyid");

                    b.HasKey("Id");

                    b.HasIndex("Cegid");

                    b.HasIndex("Telephelyid");

                    b.ToTable("allas", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskapcsolattarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int>("Kapcsolattartoid")
                        .HasColumnType("int")
                        .HasColumnName("kapcsolattartoid");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.HasIndex("Kapcsolattartoid");

                    b.ToTable("allaskapcsolattarto", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskerdes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int>("Kerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kerdesid");

                    b.Property<int>("Kor")
                        .HasColumnType("int")
                        .HasColumnName("kor");

                    b.Property<int?>("Sorszam")
                        .HasColumnType("int")
                        .HasColumnName("sorszam");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.HasIndex("Kerdesid");

                    b.ToTable("allaskerdes", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allasvizsgalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int>("Felhasznaloid")
                        .HasColumnType("int")
                        .HasColumnName("felhasznaloid");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.HasIndex("Felhasznaloid");

                    b.ToTable("allasvizsgalo", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Ceg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cegnev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cegnev");

                    b.Property<string>("Cegtipus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cegtipus");

                    b.Property<int>("Felhasznaloid")
                        .HasColumnType("int")
                        .HasColumnName("felhasznaloid");

                    b.Property<int>("Fotelephelyid")
                        .HasColumnType("int")
                        .HasColumnName("fotelephelyid");

                    b.Property<string>("Kapcsolattarto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kapcsolattarto");

                    b.Property<string>("Kapcsolattartonev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kapcsolattartonev");

                    b.Property<byte[]>("Kep")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("kep");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("leiras");

                    b.Property<string>("Levelezesicim")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("levelezesicim");

                    b.Property<int?>("Mobiltelefon")
                        .HasColumnType("int")
                        .HasColumnName("mobiltelefon");

                    b.Property<int?>("Telefon")
                        .HasColumnType("int")
                        .HasColumnName("telefon");

                    b.HasKey("Id");

                    b.HasIndex("Fotelephelyid");

                    b.ToTable("ceg", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Cegtelephely", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Cegid")
                        .HasColumnType("int")
                        .HasColumnName("cegid");

                    b.Property<string>("Irsz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("irsz");

                    b.Property<string>("Telepules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telepules");

                    b.Property<string>("Utcahazszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("utcahazszam");

                    b.HasKey("Id");

                    b.HasIndex("Cegid");

                    b.ToTable("cegtelephely", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("Adoszam")
                        .HasColumnType("bigint")
                        .HasColumnName("adoszam");

                    b.Property<bool>("Allaskereso")
                        .HasColumnType("bit")
                        .HasColumnName("allaskereso");

                    b.Property<string>("Anyjaneve")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anyjaneve");

                    b.Property<int?>("Cegid")
                        .HasColumnType("int")
                        .HasColumnName("cegid");

                    b.Property<bool>("Dolgozo")
                        .HasColumnType("bit")
                        .HasColumnName("dolgozo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jelszo");

                    b.Property<string>("Keresztnev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keresztnev");

                    b.Property<byte[]>("Oneletrajz")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("oneletrajz");

                    b.Property<DateTime?>("Szuldat")
                        .HasColumnType("datetime")
                        .HasColumnName("szuldat");

                    b.Property<string>("Szulhely")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("szulhely");

                    b.Property<int?>("Szulirsz")
                        .HasColumnType("int")
                        .HasColumnName("szulirsz");

                    b.Property<string>("Vezeteknev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vezeteknev");

                    b.HasKey("Id");

                    b.HasIndex("Cegid");

                    b.ToTable("felhasznalo", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalokompetencium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Felhasznaloid")
                        .HasColumnType("int")
                        .HasColumnName("felhasznaloid");

                    b.Property<int>("Kompetenciaid")
                        .HasColumnType("int")
                        .HasColumnName("kompetenciaid");

                    b.HasKey("Id");

                    b.HasIndex("Felhasznaloid");

                    b.HasIndex("Kompetenciaid");

                    b.ToTable("felhasznalokompetencia", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kerde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly?>("Kitoltesido")
                        .HasColumnType("time")
                        .HasColumnName("kitoltesido");

                    b.Property<int?>("Maxpont")
                        .HasColumnType("int")
                        .HasColumnName("maxpont");

                    b.Property<string>("Szoveg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("szoveg");

                    b.HasKey("Id");

                    b.ToTable("kerdes", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottallas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int>("Allaskeresoid")
                        .HasColumnType("int")
                        .HasColumnName("allaskeresoid");

                    b.Property<int>("Kitolteskezdet")
                        .HasColumnType("int")
                        .HasColumnName("kitolteskezdet");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.HasIndex("Allaskeresoid");

                    b.ToTable("kitoltottallas", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerdes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Elertpont")
                        .HasColumnType("int")
                        .HasColumnName("elertpont");

                    b.Property<int>("Kerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kerdesid");

                    b.Property<int?>("Kitolteskezdet")
                        .HasColumnType("int")
                        .HasColumnName("kitolteskezdet");

                    b.Property<int>("Kitoltottallasid")
                        .HasColumnType("int")
                        .HasColumnName("kitoltottallasid");

                    b.HasKey("Id");

                    b.HasIndex("Kerdesid");

                    b.HasIndex("Kitoltottallasid");

                    b.ToTable("kitoltottkerdes", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottvalasz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Elertpont")
                        .HasColumnType("int")
                        .HasColumnName("elertpont");

                    b.Property<string>("Fajlnev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fajlnev");

                    b.Property<byte[]>("Forrasfajl")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("forrasfajl");

                    b.Property<int>("Kitoltottkerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kitoltottkerdesid");

                    b.Property<string>("Szovegesvalasz")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("szovegesvalasz");

                    b.Property<int?>("Valaszid")
                        .HasColumnType("int")
                        .HasColumnName("valaszid");

                    b.HasKey("Id");

                    b.HasIndex("Kitoltottkerdesid");

                    b.HasIndex("Valaszid");

                    b.ToTable("kitoltottvalasz", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kompetencium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("leiras");

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipus");

                    b.HasKey("Id");

                    b.ToTable("kompetencia", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Meghivokod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cegid")
                        .HasColumnType("int")
                        .HasColumnName("cegid");

                    b.Property<DateTime>("Ervenyesseg")
                        .HasColumnType("datetime")
                        .HasColumnName("ervenyesseg");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kod");

                    b.HasKey("Id");

                    b.HasIndex("Cegid");

                    b.ToTable("meghivokod", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Valasz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Helyes")
                        .HasColumnType("int")
                        .HasColumnName("helyes");

                    b.Property<int>("Kerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kerdesid");

                    b.Property<int?>("Pontszam")
                        .HasColumnType("int")
                        .HasColumnName("pontszam");

                    b.Property<int>("Szoveg")
                        .HasColumnType("int")
                        .HasColumnName("szoveg");

                    b.HasKey("Id");

                    b.HasIndex("Kerdesid");

                    b.ToTable("valasz", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allas", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Ceg", "Ceg")
                        .WithMany("Allas")
                        .HasForeignKey("Cegid")
                        .IsRequired()
                        .HasConstraintName("FK_allas_ceg");

                    b.HasOne("Allasinterju.Database.Models.Cegtelephely", "Telephely")
                        .WithMany("Allas")
                        .HasForeignKey("Telephelyid")
                        .IsRequired()
                        .HasConstraintName("FK_allas_cegtelephely");

                    b.Navigation("Ceg");

                    b.Navigation("Telephely");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskapcsolattarto", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Allas", "Allas")
                        .WithMany("Allaskapcsolattartos")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskapcsolattarto_allas");

                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Kapcsolattarto")
                        .WithMany("Allaskapcsolattartos")
                        .HasForeignKey("Kapcsolattartoid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskapcsolattarto_felhasznalo");

                    b.Navigation("Allas");

                    b.Navigation("Kapcsolattarto");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskerdes", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Allas", "Allas")
                        .WithMany("Allaskerdes")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskerdes_allas");

                    b.HasOne("Allasinterju.Database.Models.Kerde", "Kerdes")
                        .WithMany("Allaskerdes")
                        .HasForeignKey("Kerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskerdes_kerdes");

                    b.Navigation("Allas");

                    b.Navigation("Kerdes");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allasvizsgalo", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Allas", "Allas")
                        .WithMany("Allasvizsgalos")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_allasvizsgalo_allas");

                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Felhasznalo")
                        .WithMany("Allasvizsgalos")
                        .HasForeignKey("Felhasznaloid")
                        .IsRequired()
                        .HasConstraintName("FK_allasvizsgalo_felhasznalo");

                    b.Navigation("Allas");

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Ceg", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Cegtelephely", "Fotelephely")
                        .WithMany("Cegs")
                        .HasForeignKey("Fotelephelyid")
                        .IsRequired()
                        .HasConstraintName("FK_ceg_cegtelephely");

                    b.Navigation("Fotelephely");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Cegtelephely", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Ceg", "Ceg")
                        .WithMany("Cegtelephelies")
                        .HasForeignKey("Cegid")
                        .HasConstraintName("FK_cegtelephely_ceg");

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalo", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Ceg", "Ceg")
                        .WithMany("Felhasznalos")
                        .HasForeignKey("Cegid")
                        .HasConstraintName("FK_felhasznalo_ceg");

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalokompetencium", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Felhasznalo")
                        .WithMany("Felhasznalokompetencia")
                        .HasForeignKey("Felhasznaloid")
                        .IsRequired()
                        .HasConstraintName("FK_felhasznalokompetencia_felhasznalo");

                    b.HasOne("Allasinterju.Database.Models.Kompetencium", "Kompetencia")
                        .WithMany("Felhasznalokompetencia")
                        .HasForeignKey("Kompetenciaid")
                        .IsRequired()
                        .HasConstraintName("FK_felhasznalokompetencia_kompetencia");

                    b.Navigation("Felhasznalo");

                    b.Navigation("Kompetencia");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottallas", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Allas", "Allas")
                        .WithMany("Kitoltottallas")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottallas_allas");

                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Allaskereso")
                        .WithMany("Kitoltottallas")
                        .HasForeignKey("Allaskeresoid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottallas_felhasznalo");

                    b.Navigation("Allas");

                    b.Navigation("Allaskereso");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerdes", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kerde", "Kerdes")
                        .WithMany("Kitoltottkerdes")
                        .HasForeignKey("Kerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottkerdes_kerdes");

                    b.HasOne("Allasinterju.Database.Models.Kitoltottallas", "Kitoltottallas")
                        .WithMany("Kitoltottkerdes")
                        .HasForeignKey("Kitoltottallasid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottkerdes_kitoltottallas");

                    b.Navigation("Kerdes");

                    b.Navigation("Kitoltottallas");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottvalasz", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kitoltottkerdes", "Kitoltottkerdes")
                        .WithMany("Kitoltottvalaszs")
                        .HasForeignKey("Kitoltottkerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottvalasz_kitoltottkerdes");

                    b.HasOne("Allasinterju.Database.Models.Valasz", "Valasz")
                        .WithMany("Kitoltottvalaszs")
                        .HasForeignKey("Valaszid")
                        .HasConstraintName("FK_kitoltottvalasz_valasz");

                    b.Navigation("Kitoltottkerdes");

                    b.Navigation("Valasz");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Meghivokod", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Ceg", "Ceg")
                        .WithMany("Meghivokods")
                        .HasForeignKey("Cegid")
                        .IsRequired()
                        .HasConstraintName("FK_meghivokod_ceg");

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Valasz", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kerde", "Kerdes")
                        .WithMany("Valaszs")
                        .HasForeignKey("Kerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_valasz_kerdes");

                    b.Navigation("Kerdes");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allas", b =>
                {
                    b.Navigation("Allaskapcsolattartos");

                    b.Navigation("Allaskerdes");

                    b.Navigation("Allasvizsgalos");

                    b.Navigation("Kitoltottallas");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Ceg", b =>
                {
                    b.Navigation("Allas");

                    b.Navigation("Cegtelephelies");

                    b.Navigation("Felhasznalos");

                    b.Navigation("Meghivokods");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Cegtelephely", b =>
                {
                    b.Navigation("Allas");

                    b.Navigation("Cegs");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalo", b =>
                {
                    b.Navigation("Allaskapcsolattartos");

                    b.Navigation("Allasvizsgalos");

                    b.Navigation("Felhasznalokompetencia");

                    b.Navigation("Kitoltottallas");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kerde", b =>
                {
                    b.Navigation("Allaskerdes");

                    b.Navigation("Kitoltottkerdes");

                    b.Navigation("Valaszs");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottallas", b =>
                {
                    b.Navigation("Kitoltottkerdes");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerdes", b =>
                {
                    b.Navigation("Kitoltottvalaszs");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kompetencium", b =>
                {
                    b.Navigation("Felhasznalokompetencia");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Valasz", b =>
                {
                    b.Navigation("Kitoltottvalaszs");
                });
#pragma warning restore 612, 618
        }
    }
}
