// <auto-generated />
using System;
using Allasinterju.Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Allasinterju.Database.Migrations
{
    [DbContext(typeof(AllasinterjuContext))]
    [Migration("20241120142004_Recover")]
    partial class Recover
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Allasinterju.Database.Models.Alla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cegid")
                        .HasColumnType("int")
                        .HasColumnName("cegid");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cim");

                    b.Property<DateTime?>("Hatarido")
                        .HasColumnType("datetime")
                        .HasColumnName("hatarido");

                    b.Property<TimeOnly?>("Kitoltesido")
                        .HasColumnType("time")
                        .HasColumnName("kitoltesido");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("leiras");

                    b.Property<string>("Munkakor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("munkakor");

                    b.Property<string>("Munkarend")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("munkarend");

                    b.Property<string>("Rovidleiras")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rovidleiras");

                    b.Property<string>("Telephelyszoveg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telephelyszoveg");

                    b.HasKey("Id");

                    b.HasIndex("Cegid");

                    b.ToTable("allas", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskapcsolattarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int>("Kapcsolattartoid")
                        .HasColumnType("int")
                        .HasColumnName("kapcsolattartoid");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.HasIndex("Kapcsolattartoid");

                    b.ToTable("allaskapcsolattarto", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskerdoiv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kerdesid");

                    b.Property<int>("Kerdoivid")
                        .HasColumnType("int")
                        .HasColumnName("kerdoivid");

                    b.Property<int?>("Sorszam")
                        .HasColumnType("int")
                        .HasColumnName("sorszam");

                    b.HasKey("Id")
                        .HasName("PK_allaskerdes");

                    b.HasIndex("Kerdesid");

                    b.HasIndex("Kerdoivid");

                    b.ToTable("allaskerdoiv", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskompetencium", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int>("Kompetenciaid")
                        .HasColumnType("int")
                        .HasColumnName("kompetenciaid");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.HasIndex("Kompetenciaid");

                    b.ToTable("allaskompetencia", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allasvizsgalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int>("Felhasznaloid")
                        .HasColumnType("int")
                        .HasColumnName("felhasznaloid");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.HasIndex("Felhasznaloid");

                    b.ToTable("allasvizsgalo", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Ceg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cegnev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cegnev");

                    b.Property<string>("Cegtipus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cegtipus");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Jelszo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jelszo");

                    b.Property<string>("Kapcsolattarto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kapcsolattarto");

                    b.Property<string>("Kapcsolattartonev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kapcsolattartonev");

                    b.Property<byte[]>("Kep")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("kep");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("leiras");

                    b.Property<string>("Levelezesicim")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("levelezesicim");

                    b.Property<string>("Mobiltelefon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobiltelefon");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefon");

                    b.Property<string>("Telephely")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telephely");

                    b.HasKey("Id");

                    b.ToTable("ceg", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Cegtelephely", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Cegid")
                        .HasColumnType("int")
                        .HasColumnName("cegid");

                    b.Property<string>("Cimszoveg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cimszoveg");

                    b.Property<string>("Irsz")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("irsz");

                    b.Property<string>("Telepules")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telepules");

                    b.Property<string>("Utcahazszam")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("utcahazszam");

                    b.HasKey("Id");

                    b.ToTable("cegtelephely", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Dokumentum", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<byte[]>("Fajl")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("fajl");

                    b.Property<string>("Fajlnev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fajlnev");

                    b.Property<int>("Felhasznaloid")
                        .HasColumnType("int")
                        .HasColumnName("felhasznaloid");

                    b.Property<string>("Leiras")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("leiras");

                    b.HasKey("Id");

                    b.HasIndex("Felhasznaloid");

                    b.ToTable("dokumentum", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("Adoszam")
                        .HasColumnType("bigint")
                        .HasColumnName("adoszam");

                    b.Property<bool>("Allaskereso")
                        .HasColumnType("bit")
                        .HasColumnName("allaskereso");

                    b.Property<string>("Anyjaneve")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("anyjaneve");

                    b.Property<int?>("Cegid")
                        .HasColumnType("int")
                        .HasColumnName("cegid");

                    b.Property<bool>("Dolgozo")
                        .HasColumnType("bit")
                        .HasColumnName("dolgozo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Jelszo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jelszo");

                    b.Property<byte[]>("Kep")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("kep");

                    b.Property<string>("Keresztnev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("keresztnev");

                    b.Property<string>("Leetcode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("leetcode");

                    b.Property<DateTime?>("Szuldat")
                        .HasColumnType("datetime")
                        .HasColumnName("szuldat");

                    b.Property<string>("Szulhely")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("szulhely");

                    b.Property<int?>("Szulirsz")
                        .HasColumnType("int")
                        .HasColumnName("szulirsz");

                    b.Property<string>("Vezeteknev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vezeteknev");

                    b.HasKey("Id");

                    b.ToTable("felhasznalo", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalokompetencium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Felhasznaloid")
                        .HasColumnType("int")
                        .HasColumnName("felhasznaloid");

                    b.Property<int>("Kompetenciaid")
                        .HasColumnType("int")
                        .HasColumnName("kompetenciaid");

                    b.HasKey("Id");

                    b.HasIndex("Felhasznaloid");

                    b.HasIndex("Kompetenciaid");

                    b.ToTable("felhasznalokompetencia", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kerde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Feleletvalasztos")
                        .HasColumnType("bit")
                        .HasColumnName("feleletvalasztos");

                    b.Property<int>("Kerdoivid")
                        .HasColumnType("int")
                        .HasColumnName("kerdoivid");

                    b.Property<bool?>("Kifejtos")
                        .HasColumnType("bit")
                        .HasColumnName("kifejtos");

                    b.Property<int?>("Maxpont")
                        .HasColumnType("int")
                        .HasColumnName("maxpont");

                    b.Property<string>("Programalapszoveg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("programalapszoveg");

                    b.Property<bool?>("Programozos")
                        .HasColumnType("bit")
                        .HasColumnName("programozos");

                    b.Property<string>("Programteszteset")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("programteszteset");

                    b.Property<int?>("Sorrendkerdes")
                        .HasColumnType("int")
                        .HasColumnName("sorrendkerdes");

                    b.Property<string>("Szoveg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("szoveg");

                    b.HasKey("Id");

                    b.HasIndex("Kerdoivid");

                    b.ToTable("kerdes", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kerdoiv", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int?>("Kitoltesperc")
                        .HasColumnType("int")
                        .HasColumnName("kitoltesperc");

                    b.Property<int>("Kor")
                        .HasColumnType("int")
                        .HasColumnName("kor");

                    b.Property<int?>("Maxpont")
                        .HasColumnType("int")
                        .HasColumnName("maxpont");

                    b.Property<string>("Nev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nev");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.ToTable("kerdoiv", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Allasid")
                        .HasColumnType("int")
                        .HasColumnName("allasid");

                    b.Property<int>("Allaskeresoid")
                        .HasColumnType("int")
                        .HasColumnName("allaskeresoid");

                    b.Property<DateTime>("Kitolteskezdet")
                        .HasColumnType("datetime")
                        .HasColumnName("kitolteskezdet");

                    b.HasKey("Id");

                    b.HasIndex("Allasid");

                    b.HasIndex("Allaskeresoid");

                    b.ToTable("kitoltottallas", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Elertpont")
                        .HasColumnType("int")
                        .HasColumnName("elertpont");

                    b.Property<int>("Kerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kerdesid");

                    b.Property<int?>("Kitolteskezdet")
                        .HasColumnType("int")
                        .HasColumnName("kitolteskezdet");

                    b.Property<int>("Kitoltottkerdoivid")
                        .HasColumnType("int")
                        .HasColumnName("kitoltottkerdoivid");

                    b.Property<bool?>("Programhelyes")
                        .HasColumnType("bit")
                        .HasColumnName("programhelyes");

                    b.Property<string>("Szovegesvalasz")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("szovegesvalasz");

                    b.Property<int?>("Valasztosid")
                        .HasColumnType("int")
                        .HasColumnName("valasztosid");

                    b.HasKey("Id");

                    b.HasIndex("Kerdesid");

                    b.HasIndex("Kitoltottkerdoivid");

                    b.HasIndex("Valasztosid");

                    b.ToTable("kitoltottkerdes", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerdoiv", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Befejezve")
                        .HasColumnType("bit")
                        .HasColumnName("befejezve");

                    b.Property<int>("Kerdoivid")
                        .HasColumnType("int")
                        .HasColumnName("kerdoivid");

                    b.Property<int>("Kitoltottallasid")
                        .HasColumnType("int")
                        .HasColumnName("kitoltottallasid");

                    b.Property<bool?>("Miajanlas")
                        .HasColumnType("bit")
                        .HasColumnName("miajanlas");

                    b.Property<int?>("Osszpont")
                        .HasColumnType("int")
                        .HasColumnName("osszpont");

                    b.Property<bool?>("Tovabbjut")
                        .HasColumnType("bit")
                        .HasColumnName("tovabbjut");

                    b.HasKey("Id");

                    b.HasIndex("Kerdoivid");

                    b.HasIndex("Kitoltottallasid");

                    b.ToTable("kitoltottkerdoiv", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottvalasz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Elertpont")
                        .HasColumnType("int")
                        .HasColumnName("elertpont");

                    b.Property<int>("Kitoltottkerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kitoltottkerdesid");

                    b.Property<string>("Szovegesvalasz")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("szovegesvalasz");

                    b.Property<int?>("Valaszid")
                        .HasColumnType("int")
                        .HasColumnName("valaszid");

                    b.HasKey("Id");

                    b.HasIndex("Kitoltottkerdesid");

                    b.HasIndex("Valaszid");

                    b.ToTable("kitoltottvalasz", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kompetencium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tipus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipus");

                    b.HasKey("Id");

                    b.ToTable("kompetencia", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Lefutottteszteset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Helyes")
                        .HasColumnType("int")
                        .HasColumnName("helyes");

                    b.Property<int?>("Kimenet")
                        .HasColumnType("int")
                        .HasColumnName("kimenet");

                    b.Property<int>("Kitoltottkerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kitoltottkerdesid");

                    b.Property<int>("Tesztesetid")
                        .HasColumnType("int")
                        .HasColumnName("tesztesetid");

                    b.HasKey("Id");

                    b.HasIndex("Kitoltottkerdesid");

                    b.HasIndex("Tesztesetid");

                    b.ToTable("lefutottteszteset", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Meghivokod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cegid")
                        .HasColumnType("int")
                        .HasColumnName("cegid");

                    b.Property<DateTime?>("Ervenyesseg")
                        .HasColumnType("datetime")
                        .HasColumnName("ervenyesseg");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kod");

                    b.HasKey("Id");

                    b.HasIndex("Cegid");

                    b.ToTable("meghivokod", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Teszteset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Bemenet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bemenet");

                    b.Property<int>("Kerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kerdesid");

                    b.Property<string>("Kimenet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kimenet");

                    b.HasKey("Id");

                    b.HasIndex("Kerdesid");

                    b.ToTable("teszteset", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Valasz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Helyes")
                        .HasColumnType("bit")
                        .HasColumnName("helyes");

                    b.Property<int>("Kerdesid")
                        .HasColumnType("int")
                        .HasColumnName("kerdesid");

                    b.Property<int?>("Pontszam")
                        .HasColumnType("int")
                        .HasColumnName("pontszam");

                    b.Property<string>("Szoveg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("szoveg");

                    b.HasKey("Id");

                    b.HasIndex("Kerdesid");

                    b.ToTable("valasz", (string)null);
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Alla", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Ceg", "Ceg")
                        .WithMany("Allas")
                        .HasForeignKey("Cegid")
                        .IsRequired()
                        .HasConstraintName("FK_allas_ceg");

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskapcsolattarto", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Alla", "Allas")
                        .WithMany("Allaskapcsolattartos")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskapcsolattarto_allas");

                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Kapcsolattarto")
                        .WithMany("Allaskapcsolattartos")
                        .HasForeignKey("Kapcsolattartoid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskapcsolattarto_felhasznalo");

                    b.Navigation("Allas");

                    b.Navigation("Kapcsolattarto");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskerdoiv", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kerde", "Kerdes")
                        .WithMany("Allaskerdoivs")
                        .HasForeignKey("Kerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskerdoiv_kerdes");

                    b.HasOne("Allasinterju.Database.Models.Kerdoiv", "Kerdoiv")
                        .WithMany("Allaskerdoivs")
                        .HasForeignKey("Kerdoivid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskerdoiv_kerdoiv");

                    b.Navigation("Kerdes");

                    b.Navigation("Kerdoiv");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allaskompetencium", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Alla", "Allas")
                        .WithMany("Allaskompetencia")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskompetencia_allas");

                    b.HasOne("Allasinterju.Database.Models.Kompetencium", "Kompetencia")
                        .WithMany("Allaskompetencia")
                        .HasForeignKey("Kompetenciaid")
                        .IsRequired()
                        .HasConstraintName("FK_allaskompetencia_kompetencia");

                    b.Navigation("Allas");

                    b.Navigation("Kompetencia");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Allasvizsgalo", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Alla", "Allas")
                        .WithMany("Allasvizsgalos")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_allasvizsgalo_allas");

                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Felhasznalo")
                        .WithMany("Allasvizsgalos")
                        .HasForeignKey("Felhasznaloid")
                        .IsRequired()
                        .HasConstraintName("FK_allasvizsgalo_felhasznalo");

                    b.Navigation("Allas");

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Dokumentum", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Felhasznalo")
                        .WithMany("Dokumenta")
                        .HasForeignKey("Felhasznaloid")
                        .IsRequired()
                        .HasConstraintName("FK_dokumentum_felhasznalo");

                    b.Navigation("Felhasznalo");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalokompetencium", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Felhasznalo")
                        .WithMany("Felhasznalokompetencia")
                        .HasForeignKey("Felhasznaloid")
                        .IsRequired()
                        .HasConstraintName("FK_felhasznalokompetencia_felhasznalo");

                    b.HasOne("Allasinterju.Database.Models.Kompetencium", "Kompetencia")
                        .WithMany("Felhasznalokompetencia")
                        .HasForeignKey("Kompetenciaid")
                        .IsRequired()
                        .HasConstraintName("FK_felhasznalokompetencia_kompetencia");

                    b.Navigation("Felhasznalo");

                    b.Navigation("Kompetencia");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kerde", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kerdoiv", "Kerdoiv")
                        .WithMany("Kerdes")
                        .HasForeignKey("Kerdoivid")
                        .IsRequired()
                        .HasConstraintName("FK_kerdes_kerdoiv");

                    b.Navigation("Kerdoiv");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kerdoiv", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Alla", "Allas")
                        .WithMany("Kerdoivs")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_kerdoiv_allas");

                    b.Navigation("Allas");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottalla", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Alla", "Allas")
                        .WithMany("Kitoltottallas")
                        .HasForeignKey("Allasid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottallas_allas");

                    b.HasOne("Allasinterju.Database.Models.Felhasznalo", "Allaskereso")
                        .WithMany("Kitoltottallas")
                        .HasForeignKey("Allaskeresoid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottallas_felhasznalo");

                    b.Navigation("Allas");

                    b.Navigation("Allaskereso");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerde", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kerde", "Kerdes")
                        .WithMany("Kitoltottkerdes")
                        .HasForeignKey("Kerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottkerdes_kerdes");

                    b.HasOne("Allasinterju.Database.Models.Kitoltottkerdoiv", "Kitoltottkerdoiv")
                        .WithMany("Kitoltottkerdes")
                        .HasForeignKey("Kitoltottkerdoivid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottkerdes_kitoltottallas");

                    b.HasOne("Allasinterju.Database.Models.Valasz", "Valasztos")
                        .WithMany("Kitoltottkerdes")
                        .HasForeignKey("Valasztosid")
                        .HasConstraintName("FK_kitoltottkerdes_valasz");

                    b.Navigation("Kerdes");

                    b.Navigation("Kitoltottkerdoiv");

                    b.Navigation("Valasztos");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerdoiv", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kerdoiv", "Kerdoiv")
                        .WithMany("Kitoltottkerdoivs")
                        .HasForeignKey("Kerdoivid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottkerdoiv_kerdoiv");

                    b.HasOne("Allasinterju.Database.Models.Kitoltottalla", "Kitoltottallas")
                        .WithMany("Kitoltottkerdoivs")
                        .HasForeignKey("Kitoltottallasid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottkerdoiv_kitoltottallas");

                    b.Navigation("Kerdoiv");

                    b.Navigation("Kitoltottallas");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottvalasz", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kitoltottkerde", "Kitoltottkerdes")
                        .WithMany("Kitoltottvalaszs")
                        .HasForeignKey("Kitoltottkerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_kitoltottvalasz_kitoltottkerdes");

                    b.HasOne("Allasinterju.Database.Models.Valasz", "Valasz")
                        .WithMany("Kitoltottvalaszs")
                        .HasForeignKey("Valaszid")
                        .HasConstraintName("FK_kitoltottvalasz_valasz");

                    b.Navigation("Kitoltottkerdes");

                    b.Navigation("Valasz");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Lefutottteszteset", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kitoltottkerde", "Kitoltottkerdes")
                        .WithMany("Lefutotttesztesets")
                        .HasForeignKey("Kitoltottkerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_lefutottteszteset_kitoltottkerdes");

                    b.HasOne("Allasinterju.Database.Models.Teszteset", "Teszteset")
                        .WithMany("Lefutotttesztesets")
                        .HasForeignKey("Tesztesetid")
                        .IsRequired()
                        .HasConstraintName("FK_lefutottteszteset_teszteset");

                    b.Navigation("Kitoltottkerdes");

                    b.Navigation("Teszteset");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Meghivokod", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Ceg", "Ceg")
                        .WithMany("Meghivokods")
                        .HasForeignKey("Cegid")
                        .IsRequired()
                        .HasConstraintName("FK_meghivokod_ceg");

                    b.Navigation("Ceg");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Teszteset", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kerde", "Kerdes")
                        .WithMany("Tesztesets")
                        .HasForeignKey("Kerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_teszteset_kerdes");

                    b.Navigation("Kerdes");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Valasz", b =>
                {
                    b.HasOne("Allasinterju.Database.Models.Kerde", "Kerdes")
                        .WithMany("Valaszs")
                        .HasForeignKey("Kerdesid")
                        .IsRequired()
                        .HasConstraintName("FK_valasz_kerdes");

                    b.Navigation("Kerdes");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Alla", b =>
                {
                    b.Navigation("Allaskapcsolattartos");

                    b.Navigation("Allaskompetencia");

                    b.Navigation("Allasvizsgalos");

                    b.Navigation("Kerdoivs");

                    b.Navigation("Kitoltottallas");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Ceg", b =>
                {
                    b.Navigation("Allas");

                    b.Navigation("Meghivokods");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Felhasznalo", b =>
                {
                    b.Navigation("Allaskapcsolattartos");

                    b.Navigation("Allasvizsgalos");

                    b.Navigation("Dokumenta");

                    b.Navigation("Felhasznalokompetencia");

                    b.Navigation("Kitoltottallas");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kerde", b =>
                {
                    b.Navigation("Allaskerdoivs");

                    b.Navigation("Kitoltottkerdes");

                    b.Navigation("Tesztesets");

                    b.Navigation("Valaszs");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kerdoiv", b =>
                {
                    b.Navigation("Allaskerdoivs");

                    b.Navigation("Kerdes");

                    b.Navigation("Kitoltottkerdoivs");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottalla", b =>
                {
                    b.Navigation("Kitoltottkerdoivs");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerde", b =>
                {
                    b.Navigation("Kitoltottvalaszs");

                    b.Navigation("Lefutotttesztesets");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kitoltottkerdoiv", b =>
                {
                    b.Navigation("Kitoltottkerdes");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Kompetencium", b =>
                {
                    b.Navigation("Allaskompetencia");

                    b.Navigation("Felhasznalokompetencia");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Teszteset", b =>
                {
                    b.Navigation("Lefutotttesztesets");
                });

            modelBuilder.Entity("Allasinterju.Database.Models.Valasz", b =>
                {
                    b.Navigation("Kitoltottkerdes");

                    b.Navigation("Kitoltottvalaszs");
                });
#pragma warning restore 612, 618
        }
    }
}
